- docs/index.md
Address, at least in part, iss #27
> subscriber and callback are the same

- docs/index.md
open-patient-chart and close-patient-chart, not patient-open-chart nor patient-chart-open
Fixes #38
> fix event names to be consistent - typo

- docs/index.md
Fixes #28
Add optional capability for client to query current context
> Add capability for client to query current context

- CODE_OF_CONDUCT.md
- GOVERNANCE.md
Hey @NiklasSvenzen , @daliboz , @lbergnehr ,
Will you please review this proposed code of conduct and governance additions?
I think that this change should require unanimous committer approval. 
Isaac
p.s Niklas, are there really no hyphens/apostrophes in your name? (There aren't on your linkedin nor github profiles).
> Create code of conduct & governance

- docs/launch-scenarios.md
Fixes #62 
heavily related to #59
> better describe non-oauth scenarios

- docs/specification/May2019Ballot.md
Added section on Event Notification Errors
> Sync error clarification

- docs/security-considerations.md
> Ballot-Fixes-Update security-considerations.md

- docs/specification/STU1.md
Fixes to the following issues: #94, #134, #135, #195, #196, #197, #198, #199, #200, #235, #239
> Intent verification section fixes

- docs/specification/STU1.md
Fixes to: #202, #236, #204, #203, #159, #137, #96, #95, #247, #207, #206, #205, #231, #232
> Event notification section fixes

- docs/security-considerations.md
- docs/specification/STU1.md
Fixes to issues: #92, #130, #131, #132, #184, #186, #187, #188, #189, #190
> Subscription request section fixes

- docs/specification/STU1.md
Addresses issues #193, #173, #103, and #93
> Fixes to subscription denial section

- docs/specification/May2019Ballot.md
Not touching the event example tables since they may be moving out of the spec
Addresses #241
> Add table names and references

- docs/specification/STU1.md
Fixes #245
This change is not substantive.
> non-RESTful HTTP methods

- docs/specification/STU1.md
Fixes #174, #111
Not substantive
> STU vs 1.0 vs 1.1

- docs/specification/STU1.md
> Fixes to unsubscribe section

- docs/index.md
- docs/security-considerations.md
- docs/specification/STU1.md
as reported by mkdocs local build
non-substantive
> Fix broken links

- docs/specification/STU1.md
> editorial fixes for STU1

- docs/specification/STU1.md
> STU1 clean-up

- docs/launch-scenarios.md
minimal, non-functional change.
> fix link in launch scenarios

- docs/specification/STU2.md
- mkdocs.yml
Add new STU2.md spec file, update menu to point to it.
> begin STU2 reconciliation

- docs/specification/STU2.md
> Revert "Update STU2.md"

- docs/specification/STU2.md
Issues addressed:
* FHIR-25655
* FHIR-25838
* FHIR-25839
* FHIR-25840
* FHIR-25841
* FHIR-25843
* FHIR-25846
* FHIR-25848
> Simple wording fixes to Event Notification section

- docs/specification/STU2.md
Addresses issues
- https://jira.hl7.org/browse/FHIR-25851
- https://jira.hl7.org/browse/FHIR-25656
> Stu2 event notification errors and spec ordering

- docs/specification/STU2.md
communicating wss url, per continued discussion on #303 and Connectathon 25
> switch from Content-Location to http body for

- docs/specification/STU2.md
- docs/syncconsiderations.md
FHIR-27827
FHIR-25812
FHIR-25432
FHIR-25869
> Small stu2 issues

- docs/specification/STU2.md
Reading through your awesome work on STU2 and stumbled upon a formatting issue.
Was missing a `| ------`
> Fix table format

- docs/events/imagingstudy-close.md
- docs/events/imagingstudy-open.md
- docs/events/patient-close.md
- docs/events/patient-open.md
- docs/events/syncerror.md
- docs/events/template.md
- docs/events/userhibernate.md
- docs/events/userlogout.md
* Medication records number -> Medical record number.
* The `<mark>` tag was "too close" to the ` ```json `. I hope this translates well to MK docs.
> Minor event example fixes

- docs/specification/STU2.md
> Cleanup stu2 for publish

- docs/specification/STU2.md
following STU2 ballot reconciliation
> update revision history

- docs/events/syncerror.md
- docs/specification/STU2.md
Fixes https://jira.hl7.org/browse/FHIR-27555
> add eventname to syncerror

- docs/specification/STU2.md
Fixes: FHIR-25887, FHIR-25654, FHIR-25860
> Create Conformance section. Define CapabilityStatement extension.

- docs/specification/STU2.md
to satisfy decentralized architectures
> rejigger capability statements

- docs/events/encounter-close.md
- docs/events/encounter-open.md
- docs/events/patient-close.md
- docs/events/patient-open.md
> Add encounter-open,close

- input/jira/FHIR-fhircast.xml
[] Ultimately, need to update: https://github.com/HL7/JIRA-Spec-Artifacts/blob/master/xml/FHIR-fhircast.xml
> attempt to correct copy-paste sdc urls to fhircast

- suppressed-messages.txt
Creating missing file required by QA
> Create suppressed messages.txt

- suppressed-messages.txt
> Add three more warnings

- input/ignoreWarnings.txt
- suppressed-messages.txt
> 20220325 ajulian fix suppressed messagea

- README.md
per HL7 requirements we need to add the ANSI anti-trust statement
> Update README.md to apply Ansi anti-trust.

- package-list.json
The "path" for version: current should be ci build https://build.fhir.org/ig/HL7/fhircast-docs. Try again
> Merging package-list.json with path changes 

- input/jira/FHIR-fhircast.xml
- package-list.json
- sushi-config.yaml
> finish lynns changes 

- input/pagecontent/2-9-GetCurrentContext.md
In response to:  https://jira.hl7.org/browse/FHIR-37326
> current context = most recent open

- input/pagecontent/4-2-syncconsiderations.md
Fixes: https://jira.hl7.org/browse/FHIR-37312
> better explain risk level for sync failure

- FHIR-fhircast.xml
- input/pagecontent/2-10-ContentSharing.md
Removed spaces on the left which kept IG Publisher from properly processing the md
> Correct 2.10 Formatting

- input/pagecontent/3-2-3-userlogout.md
- input/pagecontent/index.md
> JIRA 37057

- input/pagecontent/3-2-3-userlogout.md
- input/pagecontent/4-2-syncconsiderations.md
Fixes: https://jira.hl7.org/browse/FHIR-37316
> sync-considerations for userLogout, hibernate

- input/pagecontent/3-6-3-diagnosticreport-update.md
"present if one or more attributes in the patient are modified" in ImagingStudy should be "present if one or more attributes in the ImagingStudy are modified"
> Typo in Context Table

- input/pagecontent/3-6-1-diagnosticreport-open.md
Simplify Workflow section of DiagnosticReport-open
> JIRA FHIR-37100

- input/pagecontent/2-4-Subscribing.md
Addresses, at least in part, https://jira.hl7.org/browse/FHIR-37081
> app becomes subscriber only upon confirmation

- input/pagecontent/2-5-EventNotification.md
Fixes: https://jira.hl7.org/browse/FHIR-37082
> as with all events, syncerror are subscribed to

- input/pagecontent/2-5-EventNotification.md
Fixes: https://jira.hl7.org/browse/FHIR-37634
> clarify that 4xx and 5xx are permitted

- input/pagecontent/3-4-1-encounter-open.md
- input/pagecontent/3-4-2-encounter-close.md
In Encounter examples was imbedded in patient and should be a peer
> JIRA FHIR-40425

- input/pagecontent/2-10-ContentSharing.md
- input/pagecontent/3-6-4-diagnosticreport-select.md
Correct inconsistency in *-select example and improve [FHIR resource]-close wording in Hub responsibilities
> JIRA FHIR-40423

- input/images-source/DeniedSubscriptionSequence.plantuml
- input/images-source/SuccessfulWebSocketSubscriptionSequence.plantuml
- input/images-source/UnsubscriptionSequence.plantuml
- input/pagecontent/2-4-Subscribing.md
Update subscription and unsubscription sequence diagrams for consistency and clarity
> Fhir 37285 resolution

- input/pagecontent/2-7-Conformance.md
Clarify Must Support in Section 2.7 (Unable to directly add text to Artifact Summary page)
> JIRA 36731

- input/pagecontent/3-2-3-userlogout.md
Add Subscriber SHOULD send syncerror if it decides not to follow userLogout event
> User Logout syncerror note

- input/pagecontent/2-3-Events.md
Fixes: https://jira.hl7.org/browse/FHIR-37281
> improve wording; non-functional

- input/pagecontent/2-10-1-ContentSharingFHIRcastMessaging.md
- input/pagecontent/3-6-3-DiagnosticReport-update.md
Updated resolution to new normative and event catalog structure
> FHIR-36768

- input/fsh/FHIRcastDiagnosticReportClose.fsh
- input/fsh/FHIRcastDiagnosticReportOpen.fsh
- input/fsh/FHIRcastImagingStudyClose.fsh
- input/fsh/FHIRcastPatientOpen.fsh
- input/pagecontent/2-3-Events.md
Enhancement to PR#492: FHIR 40658 Contextual Subject Profiles
> Add Constraints to Ensure a Business Identifier

- input/fsh/FHIRcastObservation.fsh
- input/pagecontent/2-7-Conformance.md
- sushi-config.yaml
> Fhir 36726

- input/fsh/FHIRcastDiagnosticReportOpen.fsh
- input/fsh/FHIRcastDiagnosticReportUpdate.fsh
As discussed in October 11, 2023 meeting, add a DiagnosticReport profile for use in DiaagnosticReport-update events.
> Correction in open and add update DR resource

- input/pagecontent/3-1-1-template.md
- input/pagecontent/3-3-1-Patient-open.md
- input/pagecontent/3-3-2-Patient-close.md
- input/pagecontent/3-4-1-Encounter-open.md
- input/pagecontent/3-4-2-Encounter-close.md
- input/pagecontent/3-5-1-ImagingStudy-open.md
- input/pagecontent/3-5-2-ImagingStudy-close.md
- input/pagecontent/3-6-1-DiagnosticReport-open.md
- input/pagecontent/3-6-2-DiagnosticReport-close.md
- input/pagecontent/3-6-3-DiagnosticReport-update.md
- input/pagecontent/3-6-4-DiagnosticReport-select.md
Resolves https://jira.hl7.org/browse/FHIR-42869
> remove _elements column from events

- input/pagecontent/2-7-Conformance.md
Addresses https://jira.hl7.org/browse/FHIR-41504
> fhirVersion field - Conformance

- input/pagecontent/4-4-multitab-considerations.md
Resolves: https://jira.hl7.org/browse/FHIR-43281
> Clarify single-tab app behavior on subsequent open events

- input/pagecontent/4-2-syncconsiderations.md
https://jira.hl7.org/browse/FHIR-37116
> FHIR-37116

- input/pagecontent/4-1-launch-scenarios.md
Fix for FHIR 37109 https://jira.hl7.org/browse/FHIR-37109
> Updated unclear sentence

- input/pagecontent/2-9-GetCurrentContext.md
https://jira.hl7.org/browse/FHIR-36969
> Capitalized a lowercase SHALL

- input/pagecontent/2-10-1-ContentSharingFHIRcastMessaging.md
- input/pagecontent/2-7-Conformance.md
> Consistent terms tnolin

- input/pagecontent/2-3-Events.md
Resolution for https://jira.hl7.org/browse/FHIR-37305?jql=project%20%3D%20FHIR%20AND%20Specification%20%3D%20%22FHIRCast%20(FHIR)%20%5BFHIR-fhircast%5D%22%20AND%20statusCategory%20!%3D%20Done
> Update Selection Events

- input/pagecontent/3-6-3-DiagnosticReport-update.md
https://jira.hl7.org/browse/FHIR-37686
> applies FHIR-37686

- input/pagecontent/3-4-1-Encounter-open.md
https://jira.hl7.org/browse/FHIR-37011
> Event name changed for encounter-open to be consistent

- input/pagecontent/3-3-1-Patient-open.md
https://jira.hl7.org/browse/FHIR-37011
> Event name in section title of open title changed for consistency

- .gitignore
- FHIR-fhircast.xml
- fhircast-template/content/.index.json
- fhircast-template/content/assets/.index.json
- fhircast-template/content/assets/ico/.index.json
- fhircast-template/content/assets/images/.index.json
- fhircast-template/includes/.index.json
- fhircast-template/package/.index.json
- input/images-source/ContentExchangeBasic.plantuml
- input/images-source/ContentExchangeClosure.plantuml
- input/pagecontent/4-6-fhircast-event-content-sharing.md
Added persist content steps and diagram.
> Fhir 37128

- input/pagecontent/2_Specification.md
Fix for Jira https://jira.hl7.org/browse/FHIR-37064
> Synchronizing Context Clarification

- input/pagecontent/2-3-Events.md
Fix for https://jira.hl7.org/browse/FHIR-36082
> Event Key Names

- input/pagecontent/3-1-1-template.md
Fix for https://jira.hl7.org/browse/FHIR-37090
> Generic Text Update

- input/pagecontent/2-3-Events.md
Solution for https://jira.hl7.org/browse/FHIR-42888
> Custom events

- input/pagecontent/3-2-3-UserLogout.md
https://jira.hl7.org/browse/FHIR-36852
> User logout effect clarification

- input/pagecontent/4-2-syncconsiderations.md
https://jira.hl7.org/browse/FHIR-36987
> Fixing format of Hub sections in Table in sync considerations

- input/pagecontent/4-1-launch-scenarios.md
Fix for https://jira.hl7.org/browse/FHIR-37110
> Duplication of topic definition

- input/pagecontent/index.md
https://jira.hl7.org/browse/FHIR-36908
> Removed section 5 in introduction as normative as part of FHIR 36908

- input/pagecontent/4-6-fhircast-event-content-sharing.md
Fix for https://jira.hl7.org/browse/FHIR-36910
> Persistent Findings

- input/pagecontent/2-10-1-ContentSharingFHIRcastMessaging.md
Add explicit request for implementer feedback in 2-10-1
https://jira.hl7.org/browse/FHIR-36977
> FHIR-36977

- input/pagecontent/4-4-multitab-considerations.md
Fixes https://jira.hl7.org/browse/FHIR-37078
> prevent orphaned tab

- input/pagecontent/3-6-3-DiagnosticReport-update.md
Resolves: https://jira.hl7.org/browse/FHIR-37106
> link to transaction Bundle definition in base spec

- publication-request.json
Inspiration from https://github.com/HL7/US-Core/blob/master/publication-request.json.tmp and https://build.fhir.org/ig/HL7/fhircast-docs/qa
> correct pid and path

- FHIR-fhircast.xml
- input/fsh/CapabilityStatement.fsh
- input/fsh/FHIRcastContentUpdateBundle.fsh
- input/fsh/FHIRcastSyncErrorContext.fsh
- input/fsh/FHIRcastUserHibernateContext.fsh
- input/fsh/FHIRcastUserLogoutContext.fsh
- input/fsh/GetCurrentContextBundle.fsh
- input/fsh/ReferredToResources.fsh
- input/ignoreWarnings.txt
1. Resolve qa errors with new CompatibilityStatement example
Done: see [https://github.com/HL7/fhircast-docs/tree/STU3-quality-2](https://urldefense.com/v3/__https://github.com/HL7/fhircast-docs/tree/STU3-quality-2__;!!BJMh1g!4Y6njKfJdaOhVuc_-v0VirfaFs1dEUStzy0I5uzivaE_b6T-9F5ZmkUIpvMQDgcSTCsATWhu2arAnfCJB-m5aaE$)
1. Examples for some profiles – I'm not currently sure which profiles need examples. THere are five instances of this warning.
Done: see [https://github.com/HL7/fhircast-docs/tree/STU3-quality-2](https://urldefense.com/v3/__https://github.com/HL7/fhircast-docs/tree/STU3-quality-2__;!!BJMh1g!4Y6njKfJdaOhVuc_-v0VirfaFs1dEUStzy0I5uzivaE_b6T-9F5ZmkUIpvMQDgcSTCsATWhu2arAnfCJB-m5aaE$)
> Stu3 quality 2

- input/pagecontent/2-10-ContentSharing.md
https://jira.hl7.org/browse/FHIR-45640
removed "Forward a [FHIR resource]-select event to all Subscribers" under 2.10.1 and added it as a MAY statement in paragraph below
> updated the hub requirement for *-select event

- input/pagecontent/2-10-ContentSharing.md
Fixes: https://jira.hl7.org/browse/FHIR-43080
> content updates outside of context are experiemental

- input/pagecontent/2-5-EventNotification.md
https://jira.hl7.org/browse/FHIR-45622
> clarifying "respond" for subscription timeout

- input/pagecontent/4-2-syncconsiderations.md
https://jira.hl7.org/browse/FHIR-45718 clean up
> remove second "manually" in  4-2-syncconsiderations.md

- input/pagecontent/2_Specification.md
Resolution for https://jira.hl7.org/browse/FHIR-37066
> Specify FHIR Serialization

- input/pagecontent/2-7-Conformance.md
https://jira.hl7.org/browse/FHIR-45769
> Update 2-7-Conformance from SHOULD to SHALL

- input/pagecontent/2-10-ContentSharing.md
https://jira.hl7.org/browse/FHIR-45710
-not sure how much clearer this makes it. or if it has the same meaning still
> logical id of FHIR resource rephrasing

- sushi-config.yaml
In lieu of doing these changes as part of an unrelated fix for a balloted jira comment -- https://github.com/HL7/fhircast-docs/tree/FHIR-45784
> add inm as contact, update releaseLabel to ci-build

- input/pagecontent/2-7-Conformance.md
Fixes https://jira.hl7.org/browse/FHIR-45770
> fyi - websocketSupport likely deprecated in future

- input/pagecontent/2-5-EventNotification.md
Resolves: https://jira.hl7.org/browse/FHIR-45659
> unsubscribe following non-zero number of syncerrors

- input/pagecontent/3-6-3-DiagnosticReport-update.md
Fixes: https://jira.hl7.org/browse/FHIR-45632
> clarify number of allowd entries in transaction bundle

- input/fsh/FHIRcastCodeSystem.fsh
- input/fsh/FHIRcastUserHibernateContext.fsh
- input/fsh/FHIRcastUserLogoutContext.fsh
Fixes: https://jira.hl7.org/browse/FHIR-45626
> add system-timeout as LogoutReason

- input/pagecontent/4-4-multitab-considerations.md
Fix for https://jira.hl7.org/browse/FHIR-43282
> Expected Behavior

- input/pagecontent/3-6-3-DiagnosticReport-update.md
Fixes: https://jira.hl7.org/browse/FHIR-45783
> don't duplicate normative requirements from updates Bundle profile

- input/pagecontent/2-10-ContentSharing.md
- input/pagecontent/2-5-EventNotification.md
- input/pagecontent/2-9-GetCurrentContext.md
- input/pagecontent/4-2-3-multi-anchor-considerations.md
- input/pagecontent/4_Scenarios.md
- input/pagecontent/6_change-log.md
- sushi-config.yaml
Modifying: https://github.com/HL7/fhircast-docs/pull/615 and in relation to: https://jira.hl7.org/browse/FHIR-45610
Previously, like this:
> improve look & feel of submenu

- input/pagecontent/2-9-GetCurrentContext.md
Addresses: https://jira.hl7.org/browse/FHIR-45629
> callout on Get Current Context

- input/pagecontent/3-6-4-DiagnosticReport-select.md
to include selection of multiple Observations.
> improve select example

- .github/workflows/validate.yml
> remove IG publisher validate check

- input/fsh/FHIRcastContentUpdateBundle.fsh
- input/fsh/GetCurrentContextBundle.fsh
- sushi-config.yaml
Mtng notes: https://confluence.hl7.org/spaces/INM/pages/324975541/2025-04-29+InM+WG+FHIRCast+Agenda+Minutes
> review, update FMMs for pages
